-- MySQL Script generated by MySQL Workbench
-- 10/25/17 07:31:04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ticketms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketms` DEFAULT CHARACTER SET utf8 ;
USE `ticketms` ;

-- -----------------------------------------------------
-- Table `ticketms`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `room_no` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`check_in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`check_in` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `guest_id` INT NOT NULL,
  `room_id` INT NOT NULL,
  `check_in` DATETIME NOT NULL,
  `check_out` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_room1_idx` (`room_id` ASC),
  INDEX `fk_ticket_customer1_idx` (`guest_id` ASC),
  CONSTRAINT `fk_ticket_room1`
    FOREIGN KEY (`room_id`)
    REFERENCES `ticketms`.`room` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `ticketms`.`guest` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`department` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dept_name` VARCHAR(45) NOT NULL,
  `dept_description` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `fname` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employee_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_employee_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ticketms`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `department_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `desc` TEXT NOT NULL,
  `esc_time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_department1_idx` (`department_id` ASC),
  CONSTRAINT `fk_category_department1`
    FOREIGN KEY (`department_id`)
    REFERENCES `ticketms`.`department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`ticket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`ticket` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `time_start` DATETIME NOT NULL,
  `time_end` DATETIME NULL,
  `escalation_level` INT NOT NULL,
  `desc` TEXT NOT NULL,
  `check_in_id` INT NOT NULL,
  `emp_repond_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `emp_create_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ticket_check_in1_idx` (`check_in_id` ASC),
  INDEX `fk_ticket_employee1_idx` (`emp_repond_id` ASC),
  INDEX `fk_ticket_category1_idx` (`category_id` ASC),
  INDEX `fk_ticket_employee2_idx` (`emp_create_id` ASC),
  CONSTRAINT `fk_ticket_check_in1`
    FOREIGN KEY (`check_in_id`)
    REFERENCES `ticketms`.`check_in` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee1`
    FOREIGN KEY (`emp_repond_id`)
    REFERENCES `ticketms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `ticketms`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ticket_employee2`
    FOREIGN KEY (`emp_create_id`)
    REFERENCES `ticketms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`transcript`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`transcript` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ticket_id` INT NOT NULL,
  `description` TEXT NOT NULL,
  `time` DATETIME NOT NULL,
  `by_employee` INT NOT NULL,
  `current_emp_resp` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transcript_ticket1_idx` (`ticket_id` ASC),
  INDEX `fk_transcript_employee1_idx` (`by_employee` ASC),
  INDEX `fk_transcript_employee2_idx` (`current_emp_resp` ASC),
  CONSTRAINT `fk_transcript_ticket1`
    FOREIGN KEY (`ticket_id`)
    REFERENCES `ticketms`.`ticket` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcript_employee1`
    FOREIGN KEY (`by_employee`)
    REFERENCES `ticketms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transcript_employee2`
    FOREIGN KEY (`current_emp_resp`)
    REFERENCES `ticketms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketms`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketms`.`account` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `employee_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_account_employee1_idx` (`employee_id` ASC),
  CONSTRAINT `fk_account_employee1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `ticketms`.`employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
